name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup go-task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          echo "${PWD}/bin" >> $GITHUB_PATH
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Setup protobuf
        uses: arduino/setup-protoc@v2
        with:
          version: "24.3"
      - name: all ci steps
        run: |
          # Note: it is by design that we don't use the builder
          task apis:bootstrap
          task apis:generate
          task apis:export

      - uses: actions/upload-artifact@v3
        with:
          name: go-datatrails-common-api-gen
          path: exported/datatrails-common-api-gen

      - uses: actions/upload-artifact@v3
        with:
          name: go-datatrails-common-api-proto
          # both datatrails-common-api protos & upstream ones under a single
          # -I dir compatible location
          path: exported/proto-include

      - uses: actions/upload-artifact@v3
        with:
          name: go-datatrails-common-api-swagger
          path: exported/swagger
