name: ci
on:
  push:
  release:
    types: [published]

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup go-task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          echo "${PWD}/bin" >> $GITHUB_PATH
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Setup protobuf
        uses: arduino/setup-protoc@v2
        with:
          version: "24.3"
      - name: Generate and export
        run: |
          # Note: it is by design that we don't use the builder
          task apis:bootstrap
          task apis:generate
          task apis:export

      - name: Show exports
        working-directory: exported/
        run: find . -type d

      - name: Publish release artifacts
        if: ${{ github.event_name == 'release' }}
        env:
          GH_TOKEN: ${{ github.token }}
        working-directory: exported
        run: |
          TAG="$(echo "${GITHUB_REF}" | grep tags | grep -o "[^/]*$" || true)"

          # this test will fail if the event type is not 'published'
          if [ -z "$TAG" ]; then
            echo "::error ::This is not a tagged release"
            exit 1
          fi

          tar -czf proto-include.tar.gz proto-include
          gh release upload $TAG proto-include.tar.gz

          tar -czf swagger.tar.gz swagger
          gh release upload $TAG swagger.tar.gz

          tar -czf go-datatrails-common-api-gen.tar.gz go-datatrails-common-api-gen
          gh release upload $TAG go-datatrails-common-api-gen.tar.gz